### ISSUE TITLE
Esprima compatibility

### ISSUE THREAD

**Issue by BlueHotDog** [rusty-ecma/RESSA#26]
Hi, was wondering if this planned to be ESPrima compatible?

**Comment by FreeMasen** [comment]
Ideally yes. I would love for the AST to be serialized to the same json as ESPrima. At this point I have not put much energy into that.

One of the biggest concerns is that the AST doesn't currently include a `sourceLocation` as dictated by [ESTREE](https://github.com/estree/estree).

I believe the issue related to that was moved to [resast](https://github.com/FreeMasen/resast/issues)

**Comment by FreeMasen** [comment]
Since this will primarily be the concern of the AST crate, I am going to close this issue here. The above link will have the details of this issue moving forward.
