### ISSUE TITLE
Parse / write error with async functions

### ISSUE THREAD

**Issue by azw413** [rusty-ecma/RESSA#57]
I've discovered another parse error, this time with async functions :-

```async function test() { }```

Although this is a Decl::Func, when parsed it becomes a Function expression :- 

```(async function test() { });``` 

and therefore the symbol test is not found.

**Comment by FreeMasen** [comment]
good catch! I'll see if I can get something working here soon and hopefully release with the #55 issue as well

**Comment by FreeMasen** [comment]
@azw413  Just so you know I have published a new version that includes a fix for this ad #55 as version `0.7.2`

**Comment by azw413** [comment]
Great work Robert! Thanks for all your hard work. I?m off work for this week but I?ll be trying it as soon as I get back, I?ll also refactor that traversal code and email it to you to take a look at. Thanks again,Andrew On Mon, 16 Aug 2021 at 04:45, Robert Masen ***@***.***> wrote:
@azw413  Just so you know I have published a new version that includes a fix for this ad #55 as version 0.7.2

?You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
