### ISSUE TITLE
Inavlid use of es6 export syntax

### ISSUE THREAD

**Issue by Fee0** [rusty-ecma/RESSA#72]
The following code gives an InvalidExportError: 

```
class A  {
    foo() {}
}

export { A }
```

A constructor works. A getter or setter works as well. Only methods causes an error it seems.

*Tested on the source location branch

**Comment by FreeMasen** [comment]
Thank you for the bug report! I am hoping to get the source location branch published this weekend which will allow me to get things rolling on fixes like this
