### ISSUE TITLE
Export statement followed by expression

### ISSUE THREAD

**Issue by Fee0** [rusty-ecma/RESSA#77]
Following code results in an error. But only when written in one line.

`export let a; a=1;`

Works like this:

```
export let a; 
a=1;
```

It seems function `parse_export_decl` tries to consume a semicolon twice. Once inside `parse_lexical_decl` and once inside the function itself. Instead of semicolon it also accepts newline.

Can we simply remove the `consume_semicolon` call inside `parse_export_decl` ?
Is the semicolon preferred to be in the inner or outer expression?

**Comment by Fee0** [comment]
Wouldn't we get two semicolons now when we write this out?

**Comment by FreeMasen** [comment]
That is a good observation! In the PR I have up currently (#78) I move the semicolon to the outer decl instead of cloning it.

**Comment by Fee0** [comment]
Ah makes sense. Good job :)

**Comment by FreeMasen** [comment]
This was merged as part of `0.8.1`
