### ISSUE TITLE
ressa::Error is !sync and !send

### ISSUE THREAD

**Issue by Fee0** [rusty-ecma/RESSA#83]
Since `ressa::Error ` is neither `send` nor `sync` it is difficult to use it inside a multi threaded context.
Would it be reasonable to make it send and sync?

**Comment by FreeMasen** [comment]
Yes, I believe it would be reasonable to make it `Send + Sync` I believe the issue is the `Other` variant that is a wrapper around `Box<dyn Error>`. I am going to take a look today if we are even using this variant.

**Comment by FreeMasen** [comment]
This was released as part of [0.9.0-alpha.2](https://github.com/rusty-ecma/RESSA/releases/tag/v0.9.0-alpha.2)
